sudo: false
language: java
install:
- mvn -s .settings.xml install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script:
- mvn -s .settings.xml $MVN_GOAL -nsu -Dmaven.test.redirectTestOutputToFile=true
jdk:
- oraclejdk8
env:
  global:
  - FEATURE_BRANCH=$(echo ${TRAVIS_BRANCH} | grep "^.*/.*$" && echo true || echo false)
  - INTERNAL_BUILD=$(echo ${TRAVIS_REPO_SLUG} | grep -q "^SMARTRACTECHNOLOGY/.*$"
    && echo true || echo false)
  - MVN_GOAL=$([ "${TRAVIS_PULL_REQUEST}" == "false" -a "${TRAVIS_TAG}" == "" -a "${FEATURE_BRANCH}"
    == "false" -a "${INTERNAL_BUILD}" == "true" ] && echo deploy || echo install)
  - VERSION=$(mvn validate | grep Building | head -1 | sed -e 's/.* //')
  - secure: oBgJRmFLPRGd7XBwmkI3geIvijPSDtz/LKIYH5EiZqAQNXxo39+xhWKH7GwzSx1zZjcz2n5aJm5vceng1X1VSRop6/jcIPMIhsijJrq7sCKe7sWg2isegE/6Ct7dBKgEBGOKHEpgi6Q3JZfug6o1KaEmPtiAaJj/YTJFsT2pBXPr8bRFU1Te10TReVGVPzXbnMN9l89Nj2YFLBtEV3R82QHV88z7zVaIlP7v+bfejjUQ2TvypbBHFt+KuR4t2wcaswTjEPzwnqsINpC7lr+gNobbrFPxwcNlLUDhAoiMWi8oVq7akI7GXpbQKwnV9xHJDimvWMKYgVO5xq+JO2/3Qt5ahZ8uSTlafjj97xIhxc3N2mduU7WxTnOw8aV5CybMwXi0qI6mjWWj1X+UFuPrGjHHd3q67/SaTMF8MlWXQQhLDyC+2oxkpw72IbqmQEUCz8wtabChW31XLQL7V5CqOSImAf1qjchTXpaL4l9lyVsN/cLv1rkYIzqmOh6iQZEt5yoEQ2GBidyFfM/4ODeB26/UNPEFmrwRJc+WJ1WXZRRlr2IMNIvirmGv3WyG1fU59kPBdkfvwTOo9QgpIjiiJbEYsKioSBbpdKdAm2tevrxyK7g71a1a3m+zfQaGk0N7hcHqds7SyUled0dSIYouljXN0Fs0hSP6j/ZuPO+XmEE=
  - secure: l5ko4/tVsFa1tn7nEC0nJIpPgXqIvxpKunvSaPXZwM6/W9MlIT4CDmlupEVNglnuJ4Ud6sVo3zLf9/C4VTdDzF+dPUfnydpn1VUrWAt8xH2AMIH0VOdSc1A6yzZo3GxTOGVTZH4xb0TtAIzIKV2lqYXIVRD9NKgKrqr2bnl/R3LJOCWYR6Iqa2DPsBvozhwHimDW16zrdI4LiC8bsuhz4iV8KLjpsJ+gQ/Q2XQDezfHUsJuGqN52EcMbW7pWxhbevxqaJgbJSuxdAn/qwF1bJQ4cqH5YupIluTAA9LmElWrVd+ETWgd33hhjalA0Q1GSCYlOGtaIOJ3Z1ivSQsvfeqNny4KBjJJb2dw7Tit5pwjXNj3ldcmAA+4o+Bt2fJgNWjVhkfWoT/aN0pSQl8A4bjFkkqpq5gjhTNdqFo0NZah0k2eIbYSrvSWHahwPgKD5itbSXX9F73e2QDud3wc8x6rVdVHz5wsFDS8lDxS3ihJ4R6A5C6l7RRkZM7NjMjuKReFMuJdYFQCJBc9IsVROHgQEPB4nDGkhbmg6ElAEbTXM7Jg06fmzee/Ub8vTmgyZhPg6C7YzDgavOWyTD6ZfztfXbTimh+LJp65wS7ezvkyO+KLK6n/XdZDuwAf8nAD7WQ5v76OAT6yqlyRTmoMv1/LnTiy2B+t1fI3/ws9MPAY=
notifications:
  slack:
    on_success: change
    rooms:
      secure: qe6e2naGD2J6rsItTz6qqGGZN/fWcytk9WRtWPBmd3RK4rQDBuFdKUd7zZUzAJK7SB4nMCD3wQh5uOuVAgKTosd4nl+CXbRwoWh0NbfvXiIC+wYULx800sC3wB2iNVHz26OkA4SCmKI6M+97scvUx/+syfdTpVLooVVLZbJEu5r5wG29Lq2jdOb0qWH8eVHrCM+EyH2m6uKfAhAwM0Pmv40WPKLoRJGSziRlC5UVhOtsC+UatrFJAWmh6yw6Yn+jV/CYVo4U9UGU0m6N9atS6acMhYq/+e4oa9TjBOGX0RQ/BWzsdnbvE3eHGYupNyJGdzKDO+8gxEhzWVic6dYj7r66XQh8m2dZATr5gaYV6aQ5sbksY0C/OazqYtFc8dzleIcB/kEaFAwhVVNW3k94rJA80R/bOGyfTjFz6tYMeSIdG+UleB8ALmdV9y9DW5qxcGrX5Amvh/fYHiUK9z3A33fhDYW6fXkU9J/a8A2H71IO6xb6z4Rfur2Vr4BxhUIEId3IJbZE88xiI6ZNAjYhyQKc6hpLwiqKP7y+uk72er1tA0Rp1CIMbOUimFwzpRoYaJtmr70N8hd9vPa3hmy1FUZe3dvixvxJYFOO+grK8NoHCEENcH46+WqsckrHXi1VecOaMsxSfRnbiGd/JEwzRZlBhV0vVS74z9WdFB4TZ3U=
